### ISSUE TITLE
Dropdown broken since plugin ver. 1.3.1

### ISSUE THREAD

**Issue by firelad97** [getgrav/grav-plugin-bootstrapper#10]
The dropdown option is enabled in theme setting and the plugin is enabled. The dropdown in navigation bar does not work.

**Comment by flaviocopes** [comment]
@firelad97 this is a plugin, please open the issue on the theme you're using.

**Comment by firelad97** [comment]
The theme is fine when not using the plugin. The issue is coming from this plugin.

**Comment by flaviocopes** [comment]
Which theme?

**Comment by firelad97** [comment]
Grav's Bootstrap

**Comment by flaviocopes** [comment]
You mentioned "broken since plugin ver. 1.3.1", so previously did it work?

**Comment by flaviocopes** [comment]
Also, can you screenshot me your theme when the plugin is disabled?

**Comment by flaviocopes** [comment]
Ok recreated. In the latest release bootstrap.min.js was not added. 
Just switch the "Mode" option to "development" for now, will use the unminified version. Adding the minified version back in the next release

**Comment by flaviocopes** [comment]
Fixed, release issued

**Comment by firelad97** [comment]
Haha, good work. Yes, it does work before until 1.3.1 was released. Thank you!
