### ISSUE TITLE
sourcemap referenced but not present

### ISSUE THREAD

**Issue by woutgg** [getgrav/grav-plugin-bootstrapper#12]
On a Grav installation using this plugin I get a 404 error (Safari, OSX 10.10.5) in the web console for the file `<gravroot>/user/plugins/bootstrapper/css/bootstrap.min.css.map`.
Afaik this is caused by the line `/*# sourceMappingURL=bootstrap.min.css.map */` in the (minified) CSS file, which references a file that is not included in the plugin.

Just a minor thing but still, it does litter the console unnecessarily.

**Comment by rhukster** [comment]
We just use the bootstrap generated files as-is. This is being included in the boostrap.css because it's originally generated by SCSS or something. Probably is an issue for the boostrap team to remove the .map reference on minified versions.
