### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-bootstrapper#13]
Why not have an option for this?

**Comment by ghost** [comment]
Would you commit it if I added a box that lets you choose which version of Bootstrap?

**Comment by rhukster** [comment]
sure, as long as the the stable version is default.

**Comment by ghost** [comment]
Alright, cool. I know you guys are extremely busy with the new releases and life as usual, so I'll just throw this up and it will be there. I had fun working on this. [PR #14](https://github.com/getgrav/grav-plugin-bootstrapper/pull/14)
