### ISSUE TITLE
LESS / SASS Variables

### ISSUE THREAD

**Issue by jacobkossman** [getgrav/grav-plugin-bootstrapper#17]
Is it possible to include the source files for bootstrap so we can customize them (border-radius, colors, etc?)

**Comment by funilrys** [comment]
Hi @flaviocopes // @rhukster,
Sorry for the trouble, I know you have a lot to do...

I'm ready to work on this but what do you think about this question? 

[EDIT]
I just finished the sass implementation on my private branch.

**Comment by funilrys** [comment]
Hi @jacobkossman,

I'm waiting for @rhukster 's or @flaviocopes 's answers so I can send a PR to make the functionality available for everyone. 

But for now (we may have to wait for a long time)  you can implement it yourself with [the repo](https://github.com/funilrys/grav-plugin-bootstrapper-src) I created **(bootstrap 3.3.7 only for now).** 

A big thanks to @rhukster, @flaviocopes & others for the Grav development :)

**Comment by jacobkossman** [comment]
thanks @funilrys! i'm no longer developing using Grav (though I might pick it up again at some point since it's so clean) but hopefully they adopt this and other people can benefit from it.
