### ISSUE TITLE
linking local images breaks inside collapsible button

### ISSUE THREAD

**Issue by walkloud** [getgrav/grav-plugin-bootstrapper#20]
Greetings,
I have been using this plugin to create collapsible text/images - examples here
```http://ntc0.lbl.gov/~walkloud/callat/research/highlights```
If I make an `<img src="<remote_url> width=33%" />`, this works without a problem.  However, if I try and link to a local file (in my grav pages), using either the `<img />` or with the markdown `![]()`, it fails to load the image.  A sample non-working example (replace "pnc_fig.png" with any image in your `users/pages/images/` folder)
```
<button type="button" class="btn btn-info" data-toggle="collapse" data-target="#some_id">Abstract</button>

<div id="some_id" class="collapse">
Some text to collapse.
<br>
<!-- the following options fail to load the image -->
<img src="../../images/pnc_fig.png" />
![](/images/pnc_fig.png)
![](../../images/pnc_fig.png)
</div>  
```

I have verified if I move the image link outside of the `<div> </div>` collapsible button, it properly loads.  I am using bootstrapper in development mode, and I commented out all the hN (h1,h2,...) font-size so they do not override the antimatter ones.

UPDATE: I also put the figure directly in the same folder as the grav-page, and used `<img src="pnc_fig.png" />` and the figure still fails to load.

**Comment by funilrys** [comment]
Do you have an error under the console so we may help you ?
