### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by zabidok** [getgrav/grav-plugin-bootstrapper#21]
How I can use bootstrap vession 4.0*?

**Comment by tomceek** [comment]
I second that. Any plans for this?

**Comment by Astuceman** [comment]
Same

**Comment by newkind** [comment]
My PR with support for Bootstrap 4.1.1 has just been merged so you can test it guys ;)

**Comment by newkind** [comment]
This can be closed as Bootstrapper 2.0 has been released :)
