### ISSUE TITLE
Add support of Bootstrap 4.5.x

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-bootstrapper#27]
Hello, 
Is there a way the support of last version of Bootstrap (4.5.x) can be add ?
And to simplify the code, maybe the support of Bootstrap 3.x can be remove? (According to the wiki of Boostrap, the last update of Bootstrap 3.x dated from 2016)

Thanks

**Comment by m-ochyra** [comment]
I think there is a need to update Bootstrap. The current version has security vulnerabilities:
[https://snyk.io/vuln/npm:bootstrap?lh=4.1.1](https://snyk.io/vuln/npm:bootstrap?lh=4.1.1)

**Comment by rhukster** [comment]
Updated to latest and greatest
