### ISSUE TITLE
Broken urls for css/js of bootstrap 4.3.1

### ISSUE THREAD

**Issue by MatthiasHinz** [getgrav/grav-plugin-bootstrapper#42]
Hi, on my Grav instance with bootstrapper 2.0.0 the css and js links are invalid for bootstrap 4.3.1.

I get the following errors:

```
GET	https://stackpath.bootstrapcdn.com//bootstrap/4.3.1/css/bootstrap.min.css?g-cf4b94d2=
Status 404 Not Found
	
GET	https://stackpath.bootstrapcdn.com//bootstrap/4.3.1/js/bootstrap.min.js?g-cf4b94d2=
Status 404 Not Found
```
Removing the the second slash after the domain name  (/ instead of //) would resolve the issue, so I guess you would have to edit 
https://github.com/getgrav/grav-plugin-bootstrapper/blob/master/bootstrapper.php 

Thank you!

**Comment by rhukster** [comment]
Fixed and updated to all the latest and greatest versions
